apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent-login-prod
  name: agent-login-prod
  namespace: api-portal
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: agent-login-prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: agent-login-prod
    spec:
      containers:
      - image: registry.gitlab.com/scblife-development/api/portal/customer-login:agent-0.0.3-prod
        imagePullPolicy: Always
        name: agent-login-prod
        ports:
        - containerPort: 3001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-cloud
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
