apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent-login-prod
  name: agent-login-prod
  namespace: api-portal
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: agent-login-prod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
